version: '3'
services:
  nginx-service:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./conf:/etc/nginx/conf.d
    - ./logs:/wwwlogs
    - ./www:/www
    networks:
    - custom_net
    external_links:
    - xxoo
networks:
  custom_net:
    external:
      name: app_net
