version: '3'
services:
  app-service:
    image: tomcat:9.0
    environment:
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 8080:8080
    volumes:
    - ./webapps:/usr/local/tomcat/webapps
    - ./logs:/usr/local/tomcat/logs
    networks:
    - custom_net
networks:
  custom_net:
    external:
      name: app_net
