version: '3'
services:
  mysql-service:
    container_name: mysql-xxoo
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
    - "3306:3306"
    volumes:
    - ./data:/var/lib/mysql
    - ./conf:/etc/mysql/conf.d
    networks:
    - custom_net
networks:
  custom_net:
   external:
      name: app_net
